[toolchain]
channel = "stable"
components = ["rust-src", "rust-analyzer", "clippy", "rustfmt"]
targets = [
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "x86_64-linux-android",
  "i686-linux-android",
]
